### ISSUE TITLE
Unit tests fail for afck-sim-malice branch

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#139]
For the `afck-sim-malice` some of the unit tests fail:

```
failures:

---- engines::authority_round::tests::seal_with_empty_steps stdout ----
thread 'engines::authority_round::tests::seal_with_empty_steps' panicked at 'assertion failed: `(left == right)`
  left: `[128]`,
 right: `[3]`', ethcore/src/engines/authority_round/mod.rs:2217:4

---- engines::authority_round::tests::seal_empty_block_with_empty_steps stdout ----
thread 'engines::authority_round::tests::seal_empty_block_with_empty_steps' panicked at 'assertion failed: `(left == right)`
  left: `[1]`,
 right: `[4]`', ethcore/src/engines/authority_round/mod.rs:2271:4

---- snapshot::tests::proof_of_authority::fixed_to_contract_only stdout ----
thread 'snapshot::tests::proof_of_authority::fixed_to_contract_only' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Snapshot(BadEpochProof(8)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:997:5

---- snapshot::tests::proof_of_authority::fixed_to_contract_to_contract stdout ----
thread 'snapshot::tests::proof_of_authority::fixed_to_contract_to_contract' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Snapshot(BadEpochProof(8)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:997:5


failures:
    engines::authority_round::tests::seal_empty_block_with_empty_steps
    engines::authority_round::tests::seal_with_empty_steps
    snapshot::tests::proof_of_authority::fixed_to_contract_only
    snapshot::tests::proof_of_authority::fixed_to_contract_to_contract

test result: FAILED. 287 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by vkomenda** [comment]
These test failures are fixed by b50dc9b5eb630631be045fcd3c6b1f9a29dad28c.
